# Generated by Django 5.2.11 on 2026-04-23 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_add_avatar_to_gameprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='condition_type',
            field=models.CharField(choices=[('first_lesson', 'Перший завершений урок'), ('lessons_5', '5 уроків'), ('lessons_10', '10 уроків'), ('lessons_15', '15 уроків'), ('quiz_perfect', 'Ідеальний тест'), ('first_quiz', 'Перший пройдений тест'), ('quizzes_5', '5 пройдених тестів'), ('quizzes_10', '10 пройдених тестів'), ('quizzes_50', '50 пройдених тестів'), ('quizzes_100', '100 пройдених тестів'), ('streak_3', 'Вогник 3 дні'), ('streak_7', 'Вогник 7 днів'), ('streak_14', 'Вогник 14 днів'), ('points_100', '100 балів'), ('points_500', '500 балів'), ('points_1000', '1000 балів'), ('first_league', 'Вступ до ліги'), ('league_top', 'Топ місця в лізі'), ('challenge_done', 'Виконано челендж')], default='first_lesson', max_length=50, verbose_name='Умова'),
        ),
        migrations.CreateModel(
            name='GroupLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публічна')),
                ('join_code', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Код приєднання')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='league_avatars/', verbose_name='Аватар ліги')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_group_leagues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Кастомна Ліга',
                'verbose_name_plural': 'Кастомні Ліги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeagueChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва челенджу')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('goal_type', models.CharField(choices=[('points', 'Набрати бали'), ('tasks', 'Вирішити завдання')], default='tasks', max_length=20, verbose_name='Тип цілі')),
                ('target_value', models.PositiveIntegerField(verbose_name='Цільове значення')),
                ('start_date', models.DateTimeField(verbose_name='Початок')),
                ('end_date', models.DateTimeField(verbose_name='Кінець')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='courses.groupleague')),
            ],
            options={
                'verbose_name': 'Челендж ліги',
                'verbose_name_plural': 'Челенджі ліги',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='LeagueMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='courses.groupleague')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Повідомлення ліги',
                'verbose_name_plural': 'Повідомлення ліг',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeagueSeasonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=100, verbose_name='Назва сезону')),
                ('end_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершення')),
                ('winners_data', models.JSONField(default=dict, verbose_name='Результати')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_results', to='courses.groupleague')),
            ],
            options={
                'verbose_name': 'Результат сезону',
                'verbose_name_plural': 'Результати сезонів',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='GroupLeagueMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Адміністратор'), ('member', 'Учасник')], default='member', max_length=10, verbose_name='Роль')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Бали в поточному сезоні')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='courses.groupleague')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_leagues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Учасник ліги',
                'verbose_name_plural': 'Учасники ліги',
                'ordering': ['-points', 'joined_at'],
                'unique_together': {('league', 'user')},
            },
        ),
    ]
